# Generated by Django 3.2.15 on 2022-10-28 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoloDayItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SoloVisitLandmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xid', models.CharField(max_length=10)),
                ('day_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='travelapp.solodayitinerary')),
            ],
        ),
        migrations.CreateModel(
            name='SoloTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=30)),
                ('budget', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trip_start_date', models.DateField()),
                ('trip_end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='solodayitinerary',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_itinerary', to='travelapp.solotrip'),
        ),
    ]
