# Generated by Django 3.2.15 on 2023-04-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solotrip',
            name='budget',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
