# Generated by Django 3.2.15 on 2022-10-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_auto_20221028_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='solotrip',
            name='number_of_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
