# Generated by Django 3.2.15 on 2022-11-01 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_solotrip_number_of_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solodayitinerary',
            old_name='comment',
            new_name='itinerary',
        ),
    ]
