# Generated by Django 3.2.15 on 2022-11-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_rename_comment_solodayitinerary_itinerary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solodayitinerary',
            old_name='trip',
            new_name='trip_id',
        ),
        migrations.RenameField(
            model_name='solovisitlandmark',
            old_name='day_itinerary',
            new_name='day_itinerary_id',
        ),
    ]
