# Generated by Django 3.2.15 on 2022-11-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_auto_20221115_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='solovisitlandmark',
            name='name',
            field=models.CharField(default=False, max_length=64),
            preserve_default=False,
        ),
    ]
