# Generated by Django 3.2.15 on 2022-11-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0009_solovisitlandmark_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='solodayitinerary',
            name='day_budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
