# Generated by Django 3.2.15 on 2022-11-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_solodayitinerary_day_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solodayitinerary',
            name='day_budget',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
