# Generated by Django 3.2.15 on 2022-11-27 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0011_alter_solodayitinerary_day_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solodayitinerary',
            name='day_budget',
        ),
        migrations.CreateModel(
            name='SoloDayBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.PositiveIntegerField(default=0)),
                ('day_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='travelapp.solodayitinerary')),
            ],
        ),
    ]
