# Generated by Django 3.2.15 on 2022-11-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0012_auto_20221127_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='solodayitinerary',
            name='day_budget',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SoloDayBudget',
        ),
    ]
