name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        pip3 install selenium
        pip3 install webdriver-manager
        python3 manage.py runserver
        python3 manage.py test 
